groups = {
  "users": "Users",
  "devel": "Developers",
  "i18n": "Internationalization and Translations",
  "ports": "Ports",
  "bugs": "Bug tracking system",
  "misc": "Miscellaneous Debian",
  "lsb": "Linux Standard Base",
  "spi": "Software in the Public Interest",
  "other": "Other",
}

blurb = {
# First the user lists
  "users": {
    "debian-announce":           "Important announcements",
    "debian-commercial":         "Announcements of commercial products related to Debian [dead list]",
    "debian-enterprise":		 "Debian for the enterprise",
    "debian-firewall":           "Running a firewall on Debian",
    "debian-infrastructure-announce": "Infrastructure announcements",
    "debian-isp":                "Debian at Internet Service Providers",
    "debian-kde":                "KDE in Debian",
    "debian-laptop":             "Debian on mobile computers",
    "debian-news":               "Debian News, weekly and otherwise",
    "debian-news-italian":	 "Italian Debian News, weekly and otherwise",
    "debian-news-portuguese":    "Portuguese Debian News, weekly and otherwise",
    "debian-news-german":        "German Debian News, weekly and otherwise",
    "debian-news-french":        "French Debian News, weekly and otherwise",
    "debian-news-spanish":	 "Spanish Debian News, weekly and otherwise",
    "debian-security-announce":   "Security announcements",
    "debian-security":            "Security in Debian",
    "debian-user":                "Help and discussion among users of Debian",
    "debian-user-de":             "debian-user in German [dead list, see debian-user-german]",
    "debian-user-german":         "debian-user in German",
    "debian-user-spanish":        "debian-user in Spanish",
    "debian-user-swedish":        "debian-user in Swedish",
    "debian-user-portuguese":     "debian-user in Portuguese",
    "debian-user-catalan":        "debian-user in Catalan",
    "debian-user-polish":         "debian-user in Polish",
    "debian-user-french":         "debian-user in French",
    "debian-user-indonesian":     "debian-user in Indonesian",
    "debian-user-danish":         "debian-user in Danish",
    "debian-user-turkish":        "debian-user in Turkish",
    "debian-user-ukrainian":      "debian-user in Ukrainian",
    "debian-user-hungarian":      "debian-user in Hungarian",
    "debian-user-icelandic":      "debian-user in Icelandic",
    "debian-user-vietnamese":	 "debian-user in Vietnamese",
    "debian-chinese":             "debian-user in Chinese [dead list, superseded by debian-chinese-big5]",
    "debian-simplified-chinese":  "debian-user in Chinese [dead list, superseded by debian-chinese-gb]",
    "debian-chinese-big5":        "debian-user in Chinese [Big5]",
    "debian-chinese-gb":          "debian-user in Chinese [GB]",
    "debian-esperanto":           "debian-user in Esperanto",
    "debian-french":              "debian-user in French [dead list, see debian-user-french]",
    "debian-italian":             "debian-user in Italian",
    "debian-japanese":            "debian-user in Japanese",
    "debian-russian":             "debian-user in Russian",
    "debian-volatile":		 "Using the debian-volatile archive",
    "debian-volatile-announce":	 "Announcements for the debian-volatile archive",
    "debian-edu-announce":	 "Announcements for the debian-edu archive",
  },
  "devel":  {
  # Now the development lists
    "debian-accessibility":     "Making Debian more accessible to people with disabilities",
    "debian-admintool":         "Developing a comprehensive administration tool [dead list]",
    "debian-dak":	       "Debian Archive Kit / Buildd list",
    "debian-ddtp":	       "DDTP coordination",
    "debian-apache":            "Maintaining the Debian Apache (web server) and related packages",
    "debian-autobuild":         "Automatic package build daemons [dead list]",
    "debian-beowulf":           "Debian on Beowulf clusters",
    "debian-boot":              "Developing the installation system",
    "debian-gcc":               "Debian GCC Maintainers",
    "debian-cd":                "Creating Debian CD Images",
    "debian-ctte":              "Debian Technical Committee",
    "debian-ctte-private":      "Debian Technical Committee private list [dead list]",
    "debian-custom":            "Developing common infrastructure for custom Debian distributions",
    "debian-devel":             "Development of Debian",
    "debian-devel-announce":    "Announcements for developers",
    "debian-devel-games":       "Development of games in Debian",
    "debian-devel-spanish":     "Development discussions in Spanish",
    "debian-devel-french":      "Development discussions in French",
    "debian-devel-portuguese":  "Development discussions in Portuguese",
    "debian-devel-italian":     "Development discussions in Italian",
    "debian-devel-austrian":    "Development discussions among Austrians",
    "debian-debbugs":           "debbugs, the Debian bug tracking system",
    "debian-debbugs-cvs":       "debbugs CVS commits",
    "debian-desktop":           "Debian Desktop project",
    "debian-doc":               "Writing documentation for Debian",
    "debian-dpkg":              "Development of dpkg",
    "debian-dpkg-bugs":         "dpkg bug reports",
    "debian-dpkg-cvs":          "dpkg CVS commits",
    "debian-edu":               "Making Debian desirable for education purposes",
    "debian-edu-french":        "Discussion between French educational Debian-based projects",
    "debian-emacsen":           "Maintaining Emacsen",
    "debian-email":             "Generic \"grab-bag\" list for Debian-related communication",
    "debian-embedded":          "Debian on embedded systems",
    "debian-faq":               "Maintaining the FAQ [dead list]",
    "debian-flash":	       "development and use of flash technologies on Debian",
    "debian-glibc":             "Maintaining GNU C Library packages",
    "debian-gtk-gnome":         "Packages using GTK+ and/or GNOME",
    "debian-hams":              "Development of HAM Radio under Debian",
    "debian-handheld":          "Debian on handheld computers",
    "debian-ipv6":              "IPv6 Maintenance",
    "debian-java":              "Java Maintenance",
    "debian-jr":                "Making Debian desirable for children",
    "debian-kernel":            "Kernel packages in Debian",
    "debian-kernel-maint":      "Debian kernel development and discussion",
    "debian-knoppix":	       "Development of the Knoppix Live CD/DVD",
    "debian-lex":               "Making Debian desirable for lawyers",
    "debian-lint-maint":        "Maintenance of Debian `lint' tools like lintian or linda",
    "debian-lsb":               "Debian and the Linux Standard Base",
    "debian-med":               "Making Debian desirable for doctors",
    "debian-mentors":           "Helping newbie developers",
    "debian-multimedia":        "Multimedia support and applications",
    "debian-nonprofit":         "Debian for non-profit organizations [dead list]",
    "debian-ocaml-maint":       "ocaml package maintenance and development",
    "debian-openoffice":        "OpenOffice packages maintenance",
    "debian-perl":              "Perl packages maintenance",
    "debian-pilot":             "Debian on Pilot [dead list, see debian-handheld]",
    "debian-policy":            "Creating and editing Debian Policy",
    "debian-pool":              "Package pools discussion [dead list]",
    "debian-printing":	       "Debian Printing Infrastructure",
    "debian-private":           "Private discussions among developers",
    "debian-python":            "Python packages maintenance",
    "debian-ruby":              "Ruby packages maintenance",
    "debian-qa":                "Quality Assurance",
    "debian-qa-packages":       "Orphaned packages maintained by the QA group",
    "debian-qa-private":        "Quality Assurance private issues [dead list]",
    "debian-qt-kde":            "Packages using Qt and/or KDE",
    "debian-release":           "Coordinating Debian releases",
    "debian-science":	       "using debian for science and related research",
    "debian-security-tracker":  "Discussion about the Debian Security Tracker",
    "debian-sgml":              "Debian and SGML",
    "debian-snapshots":         "Building Snapshot Packages [dead list]",
    "debian-ssh":               "SSH packages maintenance",
    "debian-wnpp":              "Work-Needing and Prospective Packages",
    "debian-testing":           "Testing for the next release",
    "debian-tetex-maint":         "Coordination of the maintenance of TeX packages in Debian",
    "debian-tex-maint":         "Coordination of the maintenance of TeX packages in Debian",
    "debian-toolchain":         "Compilers, assemblers etc.", 
    "debian-webapps":	       "Web applications packaging ",
    "debian-www":               "Web pages design and maintenance",
    "debian-www-cvs":           "Web pages CVS commits",
    "debian-x":                 "Debian XFree86 packaging",
    "deity":                    "APT packages maintenance",
  },
  "i18n":  {
  # Then Internationalization and Translations
    "debian-i18n":                "Debian Internationalization",
    "debian-laespiral":           "Debian Laespiral (Spanish) [dead list]",
    "debian-l10n-spanish":        "Spanish Localization",
    "debian-l10n-french":         "French Localization",
    "debian-l10n-portuguese":     "Portuguese Localization",
    "debian-l10n-dutch":          "Dutch Localization",
    "debian-l10n-catalan":        "Catalan Localization",
    "debian-l10n-italian":        "Italian Localization",
    "debian-l10n-english":        "English Localization",
    "debian-l10n-esperanto":	 "Esperanto Localization",
    "debian-l10n-danish":         "Danish Localization",
    "debian-l10n-finnish":        "Finnish Localization",
    "debian-l10n-galician":       "Galician Localization",
    "debian-l10n-german":         "German Localization",
    "debian-l10n-greek":          "Greek Localization",
    "debian-l10n-polish":         "Polish Localization",
    "debian-l10n-turkish":        "Turkish Localization",
    "debian-l10n-hungarian":      "Hungarian Localization",
    "debian-l10n-russian":        "Russian Localization",
    "debian-l10n-romanian":	 "Romanian Localization",
    "debian-l10n-arabic":	 "Arabic Localization",
    "debian-l10n-czech":		 "Czech Localization",
    "debian-l10n-korean":	 "Korean Localization",
    "debian-l10n-swedish":	 "Swedish Localization",
    "debian-l10n-persian":        "Persian/Farsi Localization",
    "debian-l10n-kannada":	 "Kannada Localization",
    "debian-l10n-malayalam":	 "Malayalam Localization",
  },
  "ports":  {
  # Now come the ports
    "debian-alpha":       "Debian port to Alpha",
    "debian-68k":         "Debian port to m68k",
    "debian-sparc":       "Debian port to SPARC",
    "debian-ultralinux":  "Debian port to UltraSPARC [dead list, see debian-sparc]",
    "debian-powerpc":     "Debian port to PowerPC",
    "debian-arm":         "Debian port to ARM",
    "debian-bsd":         "Debian port to BSD",
    "debian-hurd":        "Debian port to Hurd",
    "debian-mips":        "Debian port to MIPS",
    "debian-parisc":      "Debian port to PA-RISC [dead list, see debian-hppa]",
    "debian-s390":        "Debian port to IBM S/390",
    "debian-ia64":        "Debian port to Intel IA-64",
    "debian-hppa":        "Debian port to HPPA",
    "debian-superh":      "Debian port to SuperH",
    "debian-win32":	 "Debian port to Win32",
    "debian-amd64":	 "Debian port to AMD64",
  },
  "bugs":  {
  # BTS
    "debian-bugs-closed":     "Debian BTS, closed bugs",
    "debian-bugs-dist":       "Debian BTS, received bugs",
    "debian-bugs-forwarded":  "Debian BTS, forwarded bugs",
    "debian-bugs-rc":         "Debian BTS, release-critical bugs",
  },
  "misc":  {
  # Misc Debian lists
    "whitelist":                      "Generic whitelist",
    "debian-admin":             "Internal list for Debian Project machine admins",
    "debian-books":                   "Discussion on books about Debian",
    "debian-changes":                 "Stable packages' upgrade announcements",
    "debian-all-changes":             "Stable binary-all packages' upgrade announcements [dead list]",
    "debian-alpha-changes":           "Stable alpha packages' upgrade announcements [dead list]",
    "debian-arm-changes":             "Stable arm packages' upgrade announcements [dead list]",
    "debian-hurd-i386-changes":       "Stable hurd-i386 packages' upgrade announcements [dead list]",
    "debian-i386-changes":            "Stable i386 packages' upgrade announcements [dead list]",
    "debian-m68k-changes":            "Stable m68k packages' upgrade announcements [dead list]",
    "debian-powerpc-changes":         "Stable powerpc packages' upgrade announcements [dead list]",
    "debian-sparc-changes":           "Stable sparc packages' upgrade announcements [dead list]",
    "debian-s390-changes":            "Stable s390 packages' upgrade announcements [dead list]",
    "debian-testing-changes":         "Testing packages' upgrade announcements",
    "debian-devel-changes":           "Unstable packages' upgrade announcements",
    "debian-devel-all-changes":       "Unstable binary-all packages' upgrade announcements [dead list]",
    "debian-devel-alpha-changes":     "Unstable binary-alpha packages' upgrade announcements [dead list]",
    "debian-devel-arm-changes":       "Unstable binary-arm packages' upgrade announcements [dead list]",
    "debian-devel-i386-changes":      "Unstable i386 packages' upgrade announcements [dead list]",
    "debian-devel-m68k-changes":      "Unstable m68k packages' upgrade announcements [dead list]",
    "debian-devel-powerpc-changes":   "Unstable powerpc packages' upgrade announcements [dead list]",
    "debian-devel-sparc-changes":     "Unstable sparc packages' upgrade announcements [dead list]",
    "debian-devel-hurd-i386-changes": "Unstable hurd-i386 packages' upgrade announcements [dead list]",
    "debian-devel-s390-changes":      "Unstable s390 packages' upgrade announcements [dead list]",
    "debian-cd-vendors":              "How to sell all the Debian CDs [dead list]",
    "debian-consultants":             "Debian consultants, paid support",
    "debian-curiosa":                 "All the funny stuff regarding Debian",
    "debian-events-eu":         "Events with Debian affiliation in Europe",
    "debian-events-na":         "Events with Debian affiliation in North America",
    "debian-events-nl":         "Events with Debian affiliation in the Netherlands",
    "debian-legal":                   "Copyright, licensing and patent issues",
    "debian-mirrors":                 "Discussions about the Debian mirror network",
    "debian-mirrors-announce":        "News and announcements regarding FTP archive mirrors",
    "debian-newmaint":          "Debian New Maintainer process discussion",
    "debian-newmaint-admin":    "New-Maintainer team administration [dead list, see debian-newmaint]",
    "debian-newmaint-discuss":  "Discussion about New-Maintainer team [dead list, see debian-newmaint]",
    "debian-project":                 "Discussions about non-technical issues in the project",
    "debian-women":	             "Discussion and collaboration involving women in Debian",
    "debian-jobs":		     "Job postings for members of the Debian community",
    "debian-publicity":               "Making Debian famous",
    "debian-vote":              "Voting announcements and discussion",
#    "debian-xxxx":                    "debian-xxxx",
  },
  "lsb":  {
  # LSB
    "lcs-eng":             "Linux Compatibility Standard [dead list]",
    "lsb-confcall":        "Linux Standard Base conference call",
    "lsb-discuss":         "Linux Standard Base general discussion",
    "lsb-impl":            "Linux Standard Base sample implementation",
    "lsb-spec":            "Linux Standard Base written standard",
    "lsb-test":            "Linux Standard Base test suite",
  },
  "spi":  {
  # SPI
    "spi-announce":    "Announcements by SPI Inc.",
    "spi-general":     "General discussion regarding SPI Inc.",
  },
  "other":  {
  # Other/Foreign
    "mptools-devel":   "Developer list for the mpTOOLS project",
    "cdwrite":         "cdwrite",
    "sart":            "Discussions and announcements about SART",
    "vgui-discuss":    "V C++ GUI Framework",
  },
};

li = {}
for categ,clists in blurb.items():
  for l,v in clists.items():
    li[l] = {"section":categ,
	     "description":v,
	     "shortname":l,
	     "list":l+'@lists.debian.org'}

